development:
  adapter: postgresql
  database: postwire_development
  username: postgres
  password:
  host: localhost
  encoding: utf8
  pool: 5

test:
  adapter: postgresql
  database: postwire_test
  pool: 5
  username: postgres
  password:
  host: localhost
  encoding: utf8

staging:
  adapter: postgresql
  database: postwire_staging
  pool: 5
  username: postgres
  password: 
  host: localhost
  encoding: utf8


